version: "3.9"
services:
 examens-api-service:
  image: mjimsas/examens-fastapi:0.1
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
